# -*- coding: utf-8 -*-
"""merge_sumários_classifica_competência_SBC_gera_habilidades.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E6k8eAWFS9yVu5fGcOwCMFCm2cqw5KsJ
"""
# ==============================================================================
# MERGE CONTEÚDOS E GRUPOS CLASSIFICADOS
# ==============================================================================
import pandas as pd
import os

# --- 1. Carregar os arquivos originais ---
file_conteudos = 'Merged_BPM_Books_Classificados.xlsx'
file_grupos = 'Grupos_vs_Competencias.xlsx'

df_conteudos = pd.read_excel(file_conteudos)
df_grupos = pd.read_excel(file_grupos)

# --- 2. Merge mantendo todas as colunas ---
df_merged = pd.merge(
    df_conteudos,
    df_grupos,
    on='group_name',
    how='left',
    suffixes=('_conteudo', '_grupo')
)

# --- 3. Salvar o resultado ---
output_file = 'conteudos_completo_com_competencias.xlsx'
df_merged.to_excel(output_file, index=False)
print(f"Arquivo de merge completo gerado: {output_file}")

